
appium.server.url=http://127.0.0.1:4723

app.package=kg.mseller.app.dev
app.activity=kg.mseller.app.MainActivity
device.name=Redmi Note 5
platform.name=Android
automation.name=UiAutomator2
new.command.timeout=120


user.phone=550032490
user.password=market123

